=== anonimpopov/final-project/description/events/created-trip/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://path.ru/events/created-trip/schema.json",
    "title": "Событие создания поездки",
    "description": "Json schema события создания поездки",
    "type": "object",
    "required": [
      "id",
      "source",
      "type",
      "datacontenttype",
      "time",
      "data"
    ],
    "properties": {
      "id": {
        "type": "string",
        "format": "uuid",
        "description": "Идентификатор события, уникальный в разрезе source",
        "example": "284655d6-0190-49e7-34e9-9b4060acc260"
      },
      "source": {
        "type": "string",
        "description": "Источник. Описывается в формате URI-REF",
        "example": "/trip"
      },
      "type": {
        "$ref": "#/$defs/eventType",
        "description": "Тип события. Описывается в формате reversed DNS"
      },
      "datacontenttype": {
        "type": "string",
        "description": "MIME-тип данных тела события",
        "example": "application/json"
      },
      "time": {
        "type": "string",
        "format": "date-time",
        "description": "Дата-время события в ISO-8601"
      },
      "data": {
        "$ref": "#/$defs/data",
        "description": "Тело события"
      }
    },
    "$defs": {
      "eventType": {
        "type": "string",
        "enum": [
          "trip.event.created"
        ]
      },
      "data": {
        "type": "object",
        "properties": {
          "trip_id": {
            "type": "string",
            "description": "Идентификатор созданной поездки"
          },
          "offer_id": {
            "type": "string",
            "description": "Идентификатор предложения по которому создана поездка"
          },
          "price": {
            "type": "object",
            "description": "Стоимость поездки",
            "properties": {
              "amount":{
                "type": "number",
                "description": "Amount expressed as a decimal number of major currency units",
                "format": "decimal"
              },
              "currency": {
                "type": "string",
                "description": "3 letter currency code as defined by ISO-4217",
                "format": "iso-4217"
              }
            },
            "required": ["amount", "currency"]
          },
          "from": {
            "$ref": "#/$defs/latLngLiteral",
            "description": "Точка отправления"
          },
          "to": {
            "$ref": "#/$defs/latLngLiteral",
            "description": "Точка завершения поездки"
          },
          "status": {
            "type": "string",
            "enum": ["DRIVER_SEARCH"]
          }
        },
        "required": [
          "trip_id",
          "offer_id",
          "price",
          "status",
          "from",
          "to"
        ]
      },
      "latLngLiteral": {
        "type": "object",
        "properties": {
          "lat": {
            "type": "number"
          },
          "lng": {
            "type": "number"
          }
        },
        "required": ["lat", "lng"]
      }
    }
  }

=== anonimpopov/final-project/description/events/created-trip/example.json
{
    "id": "284655d6-0190-49e7-34e9-9b4060acc261",
    "source": "/trip",
    "type": "trip.event.created",
    "datacontenttype": "application/json",
    "time": "2023-11-09T17:31:00Z",
    "data": {
        "trip_id": "e82c42d6-b86f-4e2a-93a2-858413acb148",
        "offer_id": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN0cmluZyIsImZyb20iOnsibGF0IjowLCJsbmciOjB9LCJ0byI6eyJsYXQiOjAsImxuZyI6MH0sImNsaWVudF9pZCI6InN0cmluZyIsInByaWNlIjp7ImFtb3VudCI6OTkuOTUsImN1cnJlbmN5IjoiUlVCIn19.fg0Bv2ONjT4r8OgFqJ2tpv67ar7pUih2LhDRCRhWW3c",
        "price": {
            "currency": "RUB",
            "amount": 100
        },
        "status": "DRIVER_SEARCH",
        "from": {
            "lat": 0,
            "lng": 0
        },
        "to": {
            "lat": 0,
            "lng": 0
        }
    }
}
