=== anonimpopov/final-project/description/commands/create-trip/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://path.ru/commands/create-trip/schema.json",
    "title": "Команда создания поездки",
    "description": "Json schema команды создания поездки",
    "type": "object",
    "required": [
      "id",
      "source",
      "type",
      "datacontenttype",
      "time",
      "data"
    ],
    "properties": {
      "id": {
        "type": "string",
        "format": "uuid",
        "description": "Идентификатор команды, уникальный в разрезе source",
        "example": "284655d6-0190-49e7-34e9-9b4060acc260"
      },
      "source": {
        "type": "string",
        "description": "Источник. Описывается в формате URI-REF",
        "example": "/client"
      },
      "type": {
        "$ref": "#/$defs/commandType",
        "description": "Тип команды. Описывается в формате reversed DNS"
      },
      "datacontenttype": {
        "type": "string",
        "description": "MIME-тип данных тела события",
        "example": "application/json"
      },
      "time": {
        "type": "string",
        "format": "date-time",
        "description": "Дата-время события в ISO-8601"
      },
      "data": {
        "$ref": "#/$defs/data",
        "description": "Тело события"
      }
    },
    "$defs": {
      "commandType": {
        "type": "string",
        "enum": [
          "trip.command.create"
        ]
      },
      "data": {
        "type": "object",
        "properties": {
          "offer_id": {
            "type": "string",
            "description": "Идентификатор предложения по которому нужно создать поездку"
          }
        },
        "required": [
          "offer_id"
        ]
      }
    }
  }

=== anonimpopov/final-project/description/commands/create-trip/example.json
{
    "id": "284655d6-0190-49e7-34e9-9b4060acc261",
    "source": "/client",
    "type": "trip.command.create",
    "datacontenttype": "application/json",
    "time": "2023-11-09T17:31:00Z",
    "data": {
        "offer_id": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN0cmluZyIsImZyb20iOnsibGF0IjowLCJsbmciOjB9LCJ0byI6eyJsYXQiOjAsImxuZyI6MH0sImNsaWVudF9pZCI6InN0cmluZyIsInByaWNlIjp7ImFtb3VudCI6OTkuOTUsImN1cnJlbmN5IjoiUlVCIn19.fg0Bv2ONjT4r8OgFqJ2tpv67ar7pUih2LhDRCRhWW3c"
    }
}
